require('dotenv').config();
const mongoose = require('mongoose');
const fs = require('fs');
const path = require('path');
const Station = require('./models/Station');

const connectDB = async () => {
    try {
        await mongoose.connect(process.env.MONGO_URI || 'mongodb://localhost:27017/traindb');
        console.log('MongoDB Connected...');
    } catch (err) {
        console.error(err.message);
        process.exit(1);
    }
};

const importData = async () => {
    try {
        await connectDB();

        // Read the stations JSON file generated by the extract script
        const stationsFile = path.join('C:', 'Users', 'umang', '.gemini', 'antigravity', 'brain', '4f063a52-8e49-40c8-89ee-ebe4c7b486d0', 'scratch', 'stations.json');
        
        if (!fs.existsSync(stationsFile)) {
            console.error(`File not found: ${stationsFile}`);
            process.exit(1);
        }

        const stationsRaw = fs.readFileSync(stationsFile, 'utf-8');
        const stations = JSON.parse(stationsRaw);

        // Delete existing
        await Station.deleteMany();
        console.log('Cleared existing stations');

        // Remove duplicates by stationCode (just in case the PDF had duplicates)
        const uniqueStationsMap = new Map();
        stations.forEach(s => {
            if (!uniqueStationsMap.has(s.stationCode)) {
                uniqueStationsMap.set(s.stationCode, s);
            }
        });
        
        const uniqueStations = Array.from(uniqueStationsMap.values());

        // Insert new
        await Station.insertMany(uniqueStations);
        console.log(`Successfully imported ${uniqueStations.length} stations!`);
        
        process.exit();
    } catch (error) {
        console.error(`Error with data import: ${error}`);
        process.exit(1);
    }
};

importData();
